from commands.help import *
from commands.registerapi import *
from commands.setmain import *
from commands.listchars import *
from commands.silence import *
from commands.unsilence import *
from commands.mutegroup import *
from commands.creategroup import *
from commands.altsof import *
from commands.charsinship import *
from commands.groupadmin import *
from commands.joingroup import *
from commands.listgroups import *
from commands.locate import *
from commands.ping import *
from commands.poll import *
from commands.xup import *
from commands.ban import *
from commands.unban import *
from commands.friend import *
from commands.unfriend import *
from commands.trust import *
from commands.untrust import *
from commands.elevate import *
from commands.unelevate import *
from commands.giveadmin import *
from commands.takeadmin import *
from commands.fm import *
from commands.linkalliance import *
from commands.linkcorp import *
from commands.linkshiptype import *
from commands.unlinkalliance import *
from commands.unlinkcorp import *
from commands.unlinkshiptype import *
from commands.unmute import *
from commands.mygroups import *
